name: 'Last successful sha'
description: 'Get sha of last successful workflow run on current branch.'
inputs:
  slack_channel:
    description: Slack channel to report result to
    required: true
  github_token:
    description: Secret GitHub API token to use for making API requests.
    default: ${{ github.token }}
    required: true
outputs:
  last_sha:
    description: "Conclusion of last workflow run on current branch"
    value: ${{ steps.last_status.outputs.last_status }}
runs:
  using: "composite"
  steps:
    - name: Get branch name
      shell: bash
      run: |
        if [[ ${GITHUB_EVENT_NAME} == "pull_request" ]]
        then
           echo "BRANCH_NAME=$(echo ${GITHUB_HEAD_REF})" >> $GITHUB_ENV
           echo "Branch name: ${GITHUB_HEAD_REF}"
        else
           echo "BRANCH_NAME=$(echo ${GITHUB_REF#refs/heads/})" >> $GITHUB_ENV
           echo "Branch name: ${GITHUB_REF#refs/heads/}"        
        fi
    - name: Get workflow id
      shell: bash
      run: |
        WORKFLOW_ID=$(curl --header 'authorization: Bearer ${{ inputs.github_token }}' \
                           --header 'content-type: application/json' \
        ${{ github.api_url }}/repos/${{ github.repository }}/actions/runs/${{ github.run_id }} | jq -r .workflow_id)
        echo "WORKFLOW_ID=$WORKFLOW_ID" >> $GITHUB_ENV
        echo "Workflow id: ${WORKFLOW_ID}"
    - name: Get previous build status
      shell: bash
      run: |
        LAST_SHA=$(curl --silent --header 'authorization: Bearer ${{ inputs.github_token }}' \
                                    --header 'content-type: application/json' \
        "${{ github.api_url }}/repos/${{ github.repository }}/actions/workflows/${{ env.WORKFLOW_ID }}/runs?per_page=1&status=completed&branch=${{ env.BRANCH_NAME }}" \
        | jq -r .workflow_runs[0].head_sha)
        echo "LAST_SHA=$LAST_SHA" >> $GITHUB_ENV
        echo "Sha of previous successful workflow: $LAST_SHA"
    - name: Report Deployment Status
      uses: slackapi/slack-github-action@v1.23.0
      with:
        channel-id: ${{ inputs.slack_channel }} 
        payload: |
          {
            "text": "${{ fromJSON('["Deployment Failed", "Deployment Successful"]')[job.status == 'success'] }}",
            "attachments": [
              {
                "color": "${{ fromJSON('["danger", "good"]')[job.status == 'success'] }}",
                "fields": [{
                  "title": "${{ github.repository }} - Version ${{ github.run_number }}",
                  "value": "<https://github.com/${{ github.repository }}/compare/${{ env.LAST_SHA }}...${{ github.sha }}|Released Diff>",
                  "short": false
                }]
              }
            ]
          }
